# Use the latest Red Hat UBI minimal image as a parent image
FROM registry.access.redhat.com/ubi9/ubi-minimal:9.5

# Argument for configuring the port
ARG MAVEN_REPO_PORT=8080
ARG MAVEN_REPO_FOLDER

# Install required packages: httpd and unzip, clean up after installation
RUN microdnf --disableplugin=subscription-manager -y install httpd \
  && microdnf --disableplugin=subscription-manager clean all

# Apache configuration adjustments
RUN echo "Mutex posixsem" >> /etc/httpd/conf/httpd.conf \
  && sed -i "s/Listen 80/Listen $MAVEN_REPO_PORT/g" /etc/httpd/conf/httpd.conf \
  && sed -i "s/#ServerName www.example.com:80/ServerName 127.0.0.1:$MAVEN_REPO_PORT/g" /etc/httpd/conf/httpd.conf \
  && sed -i "/ServerName 127.0.0.1:$MAVEN_REPO_PORT/a Header set Content-Security-Policy \"frame-ancestors 'self';\"" /etc/httpd/conf/httpd.conf \
  && sed -i "s/Options Indexes FollowSymLinks/Options +Indexes +FollowSymLinks/" /etc/httpd/conf/httpd.conf \
  && sed -i "$ a ServerTokens Prod" /etc/httpd/conf/httpd.conf \
  && sed -i "$ a ServerSignature Off" /etc/httpd/conf/httpd.conf \
  && sed -i "\$ a <Directory \"/var/www/html\">\n    Options +Indexes +FollowSymLinks\n    AllowOverride None\n    Require all granted\n    IndexOptions FancyIndexing SuppressDescription SuppressHTMLPreamble SuppressLastModified SuppressSize NameWidth=* SuppressColumnSorting SuppressIcon SuppressRules\n    HeaderName /header.html\n    ReadmeName /readme.html\n</Directory>" /etc/httpd/conf/httpd.conf \
  && chgrp -R 0 /var/log/httpd /var/run/httpd /var/www/html \
  && chmod -R g=u /var/log/httpd /var/run/httpd /var/www/html

COPY --chown=1000:1000 ./.tmp/$MAVEN_REPO_FOLDER /var/www/html/

# Remove the default welcome page to avoid conflicts
RUN rm -rf /etc/httpd/conf.d/welcome.conf

# Expose the configured port
EXPOSE $MAVEN_REPO_PORT

# Change to a non root user
USER 1000

HEALTHCHECK --interval=1m --timeout=5s CMD curl -f http://localhost:$MAVEN_REPO_PORT/ || exit 1

# Start httpd when the container launches
CMD ["httpd", "-D", "FOREGROUND"]