ARG BAMOE_VERSION_INTERNAL_ARG
ARG BAMOE_DOCKER_REGISTRY_ARG

FROM --platform=linux/amd64 $BAMOE_DOCKER_REGISTRY_ARG/management-console:$BAMOE_VERSION_INTERNAL_ARG

# Custom branding.
COPY ./.tmp/logo_reverse.svg /management-console/app/images/app_logo_rgb_fullcolor_reverse.svg
COPY ./.tmp/logo_default.svg /management-console/app/images/app_logo_rgb_fullcolor_default.svg
COPY ./.tmp/favicon.svg /management-console/app/favicon.svg


# At this point, we don't need to repeat the original EXPOSE nor ENTRYPOINT statements, so all done!
