---
apiVersion: "v2"
appVersion: "0.0.0"
description: "A Helm chart to deploy BAMOE Consoles on Kubernetes"
name: "consoles-helm-chart"
type: "application"
version: "0.0.0"
dependencies:
- name: "runtime-tools-consoles-helm-chart"
  version: "0.0.0"
