---
runtime-tools-consoles-helm-chart:
  management-console:
    ingress:
      enabled: true
    image:
      registry: "quay.io"
      account: "bamoe"
      name: "management-console"
      tag: "0.0.0"
      pullPolicy: "IfNotPresent"
global:
  ingressSource: "minikube"
  kubernetesIngressClass: "nginx"
  kubernetesClusterDomain: "localhost"
