---
name: "consoles"
runtime-tools-consoles-helm-chart:
  management-console:
    image:
      registry: "quay.io"
      account: "bamoe"
      name: "management-console"
      tag: "0.0.0"
      pullPolicy: "IfNotPresent"
global:
  ingressSource: ""
  kubernetesIngressClass: ""
  kubernetesClusterDomain: ""
  openshiftRouteDomain: ""
