version: "3.8"
services:
  kie_canvas:
    container_name: kie_canvas
    image: "quay.io/bamoe/canvas:${BAMOE_VERSION}"
    ports:
      - 9090:8080
    environment:
      KIE_SANDBOX_EXTENDED_SERVICES_URL: "http://localhost:21345"
      KIE_SANDBOX_CORS_PROXY_URL: "http://localhost:7081"
    depends_on:
      - extended_services
      - cors_proxy
  extended_services:
    container_name: extended_services
    image: "quay.io/bamoe/extended-services:${BAMOE_VERSION}"
    ports:
      - 21345:21345
  cors_proxy:
    container_name: cors_proxy
    image: "quay.io/bamoe/cors-proxy:${BAMOE_VERSION}"
    ports:
      - 7081:8080
