version: "3.8"
services:
  bamoe_canvas:
    container_name: bamoe_canvas
    image: "quay.io/bamoe/canvas:${BAMOE_VERSION}"
    ports:
      - 9090:8080
    environment:
      KIE_SANDBOX_EXTENDED_SERVICES_URL: "http://localhost:21345"
      KIE_SANDBOX_CORS_PROXY_URL: "http://localhost:7081"
    depends_on:
      - bamoe_extended_services
      - bamoe_cors_proxy
  bamoe_extended_services:
    container_name: bamoe_extended_services
    image: "quay.io/bamoe/extended-services:${BAMOE_VERSION}"
    ports:
      - 21345:21345
  bamoe_cors_proxy:
    container_name: bamoe_cors_proxy
    image: "quay.io/bamoe/cors-proxy:${BAMOE_VERSION}"
    ports:
      - 7081:8080
