ARG BAMOE_VERSION=9.0.0
FROM --platform=linux/amd64 docker-na.artifactory.swg-devops.com/hyc-bamoe-team-docker-local/kie-sandbox-image:$BAMOE_VERSION

ENV KIE_SANDBOX_APP_NAME='BAMOE Canvas'

ENV KIE_SANDBOX_REQUIRE_CUSTOM_COMMIT_MESSAGE='true'

ENV KIE_SANDBOX_DMN_DEV_DEPLOYMENT_BASE_IMAGE_URL='quay.io/bamoe/dmn-dev-deployment-base-image:$BAMOE_VERSION'

ENV KIE_SANDBOX_ACCELERATORS='[ \
    { \
        "name": "Quarkus", \
        "iconUrl": "https://github.com/ibm/bamoe-canvas-quarkus-accelerator/raw/$BAMOE_VERSION/quarkus-logo.png", \
        "gitRepositoryUrl": "https://github.com/ibm/bamoe-canvas-quarkus-accelerator", \
        "gitRepositoryGitRef": "$BAMOE_VERSION", \
        "dmnDestinationFolder": "src/main/resources/dmn", \
        "bpmnDestinationFolder": "src/main/resources/bpmn", \
        "otherFilesDestinationFolder": "src/main/resources/others" \
    } \
]'

ENV KIE_SANDBOX_EDITORS='[ \
    { \
        "extension": "bpmn", \
        "filePathGlob": "**/*.bpmn?(2)", \
        "editor": { \
            "resourcesPathPrefix": "gwt-editors/bpmn", \
            "path": "bpmn-envelope.html" \
        }, \
        "card": { \
            "title": "Workflow", \
            "description": "BPMN files are used to generate business workflows." \
        } \
    }, \
    { \
        "extension": "dmn", \
        "filePathGlob": "**/*.dmn", \
        "editor": { \
            "resourcesPathPrefix": "gwt-editors/dmn", \
            "path": "dmn-envelope.html" \
        }, \
        "card": { \
            "title": "Decision", \
            "description": "DMN files are used to generate decision models" \
        } \
    } \
]'

# Removing PMML assets, as they're not part of BAMOE.
RUN rm /var/www/html/samples/Sample.pmml && \
    rm /var/www/html/pmml-envelope.html && \
    rm /var/www/html/pmml-envelope.js

# Custom branding.
COPY logo_reverse.svg /var/www/html/images/app_logo_rgb_fullcolor_reverse.svg
COPY logo_default.svg /var/www/html/images/app_logo_rgb_fullcolor_default.svg
COPY favicon.svg /var/www/html/favicon.svg

# At this point, we don't need to repeat the original EXPOSE nor ENTRYPOINT statements, so all done!