FROM --platform=linux/amd64 quay.io/kie-tools/kie-sandbox-image:latest

ENV KIE_SANDBOX_APP_NAME 'BAMOE Canvas'

COPY logo_reverse.svg /var/www/html/images/app_logo_rgb_fullcolor_reverse.svg
COPY logo_default.svg /var/www/html/images/app_logo_rgb_fullcolor_default.svg
COPY favicon.svg /var/www/html/favicon.svg

EXPOSE 8080


ENTRYPOINT [ "/kie-sandbox/entrypoint.sh" ]