ARG BAMOE_VERSION_INTERNAL_ARG
ARG BAMOE_DOCKER_REGISTRY_ARG

FROM --platform=linux/amd64 $BAMOE_DOCKER_REGISTRY_ARG/kie-sandbox-webapp-image:$BAMOE_VERSION_INTERNAL_ARG

ARG BAMOE_VERSION_FINAL_ARG
ARG KIE_SANDBOX_REQUIRE_CUSTOM_COMMIT_MESSAGE_ARG
ARG KIE_SANDBOX_DEV_DEPLOYMENT_BASE_IMAGE_URL_ARG
ARG KIE_SANDBOX_DEV_DEPLOYMENT_KOGITO_QUARKUS_BLANK_APP_IMAGE_URL_ARG
ARG KIE_SANDBOX_DEV_DEPLOYMENT_DMN_FORM_WEBAPP_IMAGE_URL_ARG

ENV KIE_SANDBOX_REQUIRE_CUSTOM_COMMIT_MESSAGE=$KIE_SANDBOX_REQUIRE_CUSTOM_COMMIT_MESSAGE_ARG \
    KIE_SANDBOX_APP_NAME='BAMOE Canvas' \
    KIE_SANDBOX_DEV_DEPLOYMENT_BASE_IMAGE_URL=$KIE_SANDBOX_DEV_DEPLOYMENT_BASE_IMAGE_URL_ARG \
    KIE_SANDBOX_DEV_DEPLOYMENT_KOGITO_QUARKUS_BLANK_APP_IMAGE_URL=$KIE_SANDBOX_DEV_DEPLOYMENT_KOGITO_QUARKUS_BLANK_APP_IMAGE_URL_ARG \
    KIE_SANDBOX_DEV_DEPLOYMENT_DMN_FORM_WEBAPP_IMAGE_URL=$KIE_SANDBOX_DEV_DEPLOYMENT_DMN_FORM_WEBAPP_IMAGE_URL_ARG \
    KIE_SANDBOX_ACCELERATORS="[ \
    { \
        \"name\": \"Quarkus (Full)\", \
        \"iconUrl\": \"images/canvas_accelerator_logo_quarkus_full.png\", \
        \"gitRepositoryUrl\": \"https://github.com/ibm/bamoe-canvas-quarkus-accelerator\", \
        \"gitRepositoryGitRef\": \"$BAMOE_VERSION_FINAL_ARG-quarkus-full\", \
        \"dmnDestinationFolder\": \"src/main/resources\", \
        \"bpmnDestinationFolder\": \"src/main/resources\", \
        \"otherFilesDestinationFolder\": \"src/main/resources\" \
    }, \
    { \
        \"name\": \"Quarkus (DMN)\", \
        \"iconUrl\": \"images/canvas_accelerator_logo_quarkus_dmn.png\", \
        \"gitRepositoryUrl\": \"https://github.com/ibm/bamoe-canvas-quarkus-accelerator\", \
        \"gitRepositoryGitRef\": \"$BAMOE_VERSION_FINAL_ARG-quarkus-dmn\", \
        \"dmnDestinationFolder\": \"src/main/resources\", \
        \"bpmnDestinationFolder\": \"src/main/resources\", \
        \"otherFilesDestinationFolder\": \"src/main/resources\" \
    } \
]" \
    KIE_SANDBOX_EDITORS='[ \
    { \
        "extension": "bpmn", \
        "filePathGlob": "**/*.bpmn?(2)", \
        "editor": { \
            "resourcesPathPrefix": "gwt-editors/bpmn", \
            "path": "bpmn-envelope.html" \
        }, \
        "card": { \
            "title": "Workflow", \
            "description": "BPMN files are used to generate business workflows." \
        } \
    }, \
    { \
        "extension": "dmn", \
        "filePathGlob": "**/*.dmn", \
        "editor": { \
            "resourcesPathPrefix": "", \
            "path": "new-dmn-editor-envelope.html" \
        }, \
        "card": { \
            "title": "Decision", \
            "description": "DMN files are used to generate decision models" \
        } \
    } \
]'

# Removing PMML assets, as they're not part of BAMOE.
# Disabled until https://github.com/apache/incubator-kie-issues/issues/327 is resolved.
#RUN rm /var/www/html/samples/Sample.pmml && \
#    rm /var/www/html/pmml-envelope.html && \
#    rm /var/www/html/pmml-envelope.js

# Custom branding.
COPY ./.tmp/logo_reverse.svg /kie-sandbox/app/images/app_logo_rgb_fullcolor_reverse.svg
COPY ./.tmp/logo_default.svg /kie-sandbox/app/images/app_logo_rgb_fullcolor_default.svg
COPY ./.tmp/favicon.svg /kie-sandbox/app/favicon.svg
COPY ./.tmp/canvas_accelerators_logo.png /kie-sandbox/app/images/canvas_accelerator_logo_quarkus_full.png
COPY ./.tmp/canvas_accelerators_logo.png /kie-sandbox/app/images/canvas_accelerator_logo_quarkus_dmn.png


# At this point, we don't need to repeat the original EXPOSE nor ENTRYPOINT statements, so all done!
